services:
  gen-ja-tts:
    container_name: gen-ja-tts
    # platform: linux/amd64
    image: atotti/gen-ja-tts:latest
    working_dir: /root/app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/root/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
