_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "2":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "6": 4.46.3
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.99
freeze_text_encoder:
    value: true
global_batch_size:
    value: 2
gradient_accumulation_steps:
    value: 18
learning_rate:
    value: 0.0001
lr_scheduler_type:
    value: CONSTANT_WITH_WARMUP
max_duration_in_seconds:
    value: 20
mixed_precision:
    value: fp16
model_name_or_path:
    value: 2121-8/japanese-parler-tts-mini
num_train_epochs:
    value: 10
per_device_train_batch_size:
    value: 2
temperature:
    value: 1
warmup_steps:
    value: 50
weight_decay:
    value: 0.01
